version: "3.9"
services:
  mongodb:
    image: "mongo"
    volumes:
      - mongodata:/data/db
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app/
      - /app/node_modules
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
volumes:
  mongodata:
  logs:
